//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.1
//     from Assets/Scripts/LevelGeneration/NewInputActionMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @NewInputActionMap: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @NewInputActionMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""NewInputActionMap"",
    ""maps"": [
        {
            ""name"": ""PlayerTesting"",
            ""id"": ""a5df7299-91ed-4d01-977e-512ae936774a"",
            ""actions"": [
                {
                    ""name"": ""Test"",
                    ""type"": ""Button"",
                    ""id"": ""e5fa4497-41fb-4b2c-a517-d3d96a29039d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7cc5c811-5e21-433a-bf04-295753ee48a0"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Test"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerTesting
        m_PlayerTesting = asset.FindActionMap("PlayerTesting", throwIfNotFound: true);
        m_PlayerTesting_Test = m_PlayerTesting.FindAction("Test", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerTesting
    private readonly InputActionMap m_PlayerTesting;
    private List<IPlayerTestingActions> m_PlayerTestingActionsCallbackInterfaces = new List<IPlayerTestingActions>();
    private readonly InputAction m_PlayerTesting_Test;
    public struct PlayerTestingActions
    {
        private @NewInputActionMap m_Wrapper;
        public PlayerTestingActions(@NewInputActionMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Test => m_Wrapper.m_PlayerTesting_Test;
        public InputActionMap Get() { return m_Wrapper.m_PlayerTesting; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerTestingActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerTestingActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerTestingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerTestingActionsCallbackInterfaces.Add(instance);
            @Test.started += instance.OnTest;
            @Test.performed += instance.OnTest;
            @Test.canceled += instance.OnTest;
        }

        private void UnregisterCallbacks(IPlayerTestingActions instance)
        {
            @Test.started -= instance.OnTest;
            @Test.performed -= instance.OnTest;
            @Test.canceled -= instance.OnTest;
        }

        public void RemoveCallbacks(IPlayerTestingActions instance)
        {
            if (m_Wrapper.m_PlayerTestingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerTestingActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerTestingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerTestingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerTestingActions @PlayerTesting => new PlayerTestingActions(this);
    public interface IPlayerTestingActions
    {
        void OnTest(InputAction.CallbackContext context);
    }
}
